# Generated by Django 3.2.4 on 2024-03-27 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Email to admin of World of Craft', 'verbose_name_plural': 'Emails to admin of World of Craft'},
        ),
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, help_text='Code.', max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Email message', max_length=2200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Email subject.', max_length=100, verbose_name='Email subject'),
        ),
    ]
