# Generated by Django 3.2.4 on 2024-03-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_contact', '0002_auto_20240327_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Messages to admin of World of Craft', 'verbose_name_plural': 'Messages to admin of World of Craft'},
        ),
    ]
