# Generated by Django 3.2.4 on 2024-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_rkxcnv', upload_to='images/'),
        ),
    ]
