# Generated by Django 3.2.4 on 2024-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
