# Generated by Django 3.2.4 on 2024-04-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_profiles', '0004_profile_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
    ]
