# Generated by Django 3.2.4 on 2024-04-02 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crafts_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='owner',
        ),
        migrations.AddField(
            model_name='panel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
