# Generated by Django 3.2.4 on 2024-04-02 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crafts_panel', '0005_alter_panel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='owner',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
